export const PAYMENT_ERROR_CODES = {
  '000': 'Transaction approved.',
  '777': 'Operation completed (success code for operations where no transaction is recorded, including J2 and J5)',
  '001': 'Blocked confiscate card. Please check and enter the credit number again.',
  '002': 'Stolen confiscate card. Please check and enter the credit number again.',
  '003': 'Contact credit company to approve the transaction.',
  '004': 'Refusal. Please contact the card owner to check the reason with his credit company.',
  '005': 'Forged confiscate card.',
  '006': 'Incorrect identity number or CVV.',
  '007': 'Invalid cavv/ucaf.',
  '008': 'Invalid avs.',
  '009': 'Unsuccessful communication.',
  '010': 'Partial confirmation',
  '011': 'Transaction rejected: insufficient points/stars/miles/other benefits',
  '012': 'Unauthorized card for this terminal.',
  '013': 'Incorrect balance code',
  '014': 'Card not associated with network',
  '015': 'Expired card. Please check the expiration date again.',
  '016': 'Unauthorized currency.',
  '017': 'Unauthorized credit type for this transaction.',
  '026': 'Wrong ID number. Please check the ID number again.',
  '041': 'There is an obligation to exit for inquiry due to ceiling only for transaction with parameter J2',
  '042': 'There is an obligation to exit for inquiry not only due to ceiling, for transaction with parameter J2',
  '051': 'Missing vector 1 file.',
  '052': 'Missing vector 4 file.',
  '053': 'Missing vector 6 file.',
  '055': 'Missing vector 11 file.',
  '056': 'Missing vector 12 file.',
  '057': 'Missing vector 15 file.',
  '058': 'Missing vector 18 file.',
  '059': 'Missing vector 31 file.',
  '060': 'Missing vector 34 file.',
  '061': 'Missing vector 41 file.',
  '062': 'Missing vector 44 file.',
  '063': 'Missing vector 64 file.',
  '064': 'Missing vector 80 file.',
  '065': 'Missing vector 81 file.',
  '066': 'Missing vector 82 file.',
  '067': 'Missing vector 83 file.',
  '068': 'Missing vector 90 file.',
  '069': 'Missing vector 91 file.',
  '070': 'Missing vector 92 file.',
  '071': 'Missing vector 93 file.',
  '073': 'Missing PARAM_3_1 file.',
  '074': 'Missing PARAM_3_2 file.',
  '075': 'Missing PARAM_3_3 file.',
  '076': 'Missing PARAM_3_4 file.',
  '077': 'Missing PARAM_361 file.',
  '078': 'Missing PARAM_363 file.',
  '079': 'Missing PARAM_364 file.',
  '080': 'Missing PARAM_61 file.',
  '081': 'Missing PARAM_62 file.',
  '082': 'Missing PARAM_63 file.',
  '083': 'Missing CEIL_41 file.',
  '084': 'Missing CEIL_42 file.',
  '085': 'Missing CEIL_43 file.',
  '086': 'Missing CEIL_44 file.',
  '087': 'Missing DATA file.',
  '088': 'Missing JENR file.',
  '089': 'Missing Start file.',
  '101': 'Missing entry in vector 1',
  '103': 'Missing entry in vector 4',
  '104': 'Missing entry in vector 6',
  '106': 'Missing entry in vector 11',
  '107': 'Missing entry in vector 12',
  '108': 'Missing entry in vector 15',
  '110': 'Missing entry in vector 18',
  '111': 'Missing entry in vector 31',
  '112': 'Missing entry in vector 34',
  '113': 'Missing entry in vector 41',
  '114': 'Missing entry in vector 44',
  '116': 'Missing entry in vector 64',
  '117': 'Missing entry in vector 81',
  '118': 'Missing entry in vector 82',
  '119': 'Missing entry in vector 83',
  '120': 'Missing entry in vector 90',
  '121': 'Missing entry in vector 91',
  '122': 'Missing entry in vector 92',
  '123': 'Missing entry in vector 93',
  '141': 'Terminal not authorized to clear transaction brand',
  '142': 'Missing appropriate entry in parameters file 3.3',
  '143': 'Missing entry in club domains file 3.6.1',
  '144': 'Missing entry in club domains file 3.6.3',
  '145': 'Missing entry in club domains file 3.6.4',
  '146': 'Missing entry in ceilings file for PL cards 4.1',
  '147': 'Missing entry in ceilings file for Israeli non-PL cards method 0 4.2',
  '148': 'Missing entry in ceilings file for Israeli non-PL cards method 1 4.3',
  '149': 'Missing entry in ceilings file for tourist cards 4.4',
  '150': 'Missing entry in valid cards file - Isracard',
  '151': 'Missing entry in valid cards file - Cal',
  '152': 'Missing entry in valid cards file - future issuer',
  '182': 'Vector 4 values error.',
  '183': 'Vector 6/12 values error.',
  '186': 'Vector 18 values error.',
  '187': 'Vector 34 values error.',
  '188': 'Vector 64 values error.',
  '190': 'Vector 90 values error.',
  '191': 'Invalid data in issuer permissions vector',
  '192': 'Invalid data in parameters set',
  '193': 'Invalid data in terminal level parameters file',
  '300': 'No authorization for transaction type - acquirer authorization',
  '301': 'No authorization for currency - acquirer authorization - no acquirer approval for ISO currency. Terminal has no authorization from the acquiring credit company for foreign currency transactions.',
  '303': 'No acquirer authorization to perform transaction when card is not present - terminal has no authorization for telephone transaction.',
  '304': 'No authorization for credit - acquirer authorization - card is not authorized to perform at this terminal or no authorization for such transaction.',
  '308': 'No authorization for linking - acquirer authorization',
  '309': 'No acquirer authorization for credit at fixed time',
  '310': 'No authorization for pre-authorization number entry',
  '311': 'No authorization to perform transactions for service code 587 - terminal has no authorization for card with service code 085.',
  '312': 'No acquirer authorization for deferred credit',
  '313': 'No acquirer authorization for benefits',
  '314': 'No acquirer authorization for performers',
  '315': 'No acquirer authorization for specific performer code',
  '316': 'No acquirer authorization for loading transaction',
  '317': 'No acquirer authorization for loading/unloading in payment method code combined with currency code',
  '318': 'No acquirer authorization for currency in this credit type - no acquirer approval for ISO currency.',
  '319': 'No acquirer authorization for tip',
  '341': 'No authorization for transaction - issuer authorization',
  '342': 'No authorization for currency - issuer authorization - no brand approval for ISO currency.',
  '343': 'No issuer authorization to perform transaction when card is not present',
  '344': 'No authorization for credit - issuer authorization - card is not authorized to perform transaction with this credit type.',
  '348': 'No authorization to perform retailer-initiated authorization request',
  '349': 'No appropriate authorization to perform authorization request without transaction J5',
  '350': 'No issuer authorization for benefits',
  '351': 'No issuer authorization for deferred credit',
  '352': 'No issuer authorization for loading transaction',
  '353': 'No issuer authorization for loading/unloading in payment method code',
  '354': 'No issuer authorization for currency in this credit type - no brand approval for ISO currency.',
  '381': 'No authorization to perform contactless transaction above maximum amount',
  '382': 'In terminal defined as self-service, only self-service transactions can be performed',
  '384': 'Terminal defined as multi-provider/beneficiary - missing provider/beneficiary number',
  '385': 'In terminal defined as e-commerce terminal, eci must be transmitted',
  '401': 'Number of payments greater than maximum number of payments field value',
  '402': 'Number of payments less than minimum number of payments field value',
  '403': 'Transaction amount less than minimum amount field value for payment !!!',
  '404': 'Number of payments field not entered',
  '405': 'Missing first/fixed payment amount data',
  '406': 'Total transaction amount differs from first payment amount + fixed payment amount * number of payments - payment error - transaction amount must equal first payment + (fixed payment multiplied by number of payments) - transaction in payments with incorrect values entered. Contact software distributor.',
  '407': 'Invalid channel 2',
  '408': 'Channel 2 shorter than 37 characters - magnetic stripe too short. - Invalid magnetic stripe length entered in input file',
  '410': 'Rejection due to dcode',
  '414': 'In transaction with fixed charge date, date entered is later than transaction execution year',
  '415': 'Invalid data entered',
  '416': 'Invalid expiry date',
  '417': 'Invalid terminal number',
  '418': 'Essential parameters missing',
  '419': 'Error in transmitting clientInputPan attribute',
  '420': 'Invalid card number - in card not present transaction mode with channel 2 entry',
  '421': 'General error - invalid data',
  '422': 'Error in ISO message construction',
  '424': 'Non-numeric field',
  '425': 'Duplicate record',
  '426': 'Amount increased after credit checks performed',
  '428': 'Missing service code on card',
  '429': 'Card not valid according to valid cards file',
  '431': 'General failure.',
  '432': 'No authorization to transmit card through magnetic reader',
  '433': 'Required to transmit in PinPad',
  '434': 'Forbidden to transmit card in PinPad device',
  '435': 'Device not configured for magnetic card transmission CTL',
  '436': 'Device not configured for EMV card transmission CTL',
  '439': 'No authorization for credit type by transaction type',
  '440': 'Tourist card not authorized for this credit type',
  '441': 'No authorization to perform transaction type - card exists in vector 80',
  '442': 'Stand-in authorization verification not allowed for this acquirer',
  '443': 'Cannot perform cancellation transaction - card not found in existing terminal transactions file',
  '445': 'In immediate charge card, only immediate charge credit can be performed',
  '447': 'Wrong credit card number.',
  '448': 'Address (City, Street, House number & Zip code) is necessary.',
  '449': 'Zip code is necessary.',
  '450': 'Performer code out of range, must be in range 1-12',
  '451': 'Error during transaction record construction',
  '452': 'In loading/unloading/balance inquiry transaction, payment method code field must be entered',
  '453': 'Cannot cancel unloading transaction 7.9.3',
  '455': 'Cannot perform forced charge transaction when authorization request is required (except ceilings)',
  '456': 'Card found in transactions file with response code "card confiscated"',
  '457': 'In immediate charge card, regular charge/credit/cancellation transaction is allowed',
  '458': 'Club code out of range',
  '470': 'In installment transaction, payment amount higher than transaction amount field',
  '471': 'In installment transaction, installment payment number greater than total number of payments',
  '472': 'In charge transaction with cash, cash amount must be entered',
  '473': 'In charge transaction with cash, cash amount must be less than transaction amount',
  '474': 'Standing order initialization transaction requires J5 parameter',
  '475': 'Installment transaction requires one of the fields: number of payments or total amount',
  '476': 'Standing order installment transaction requires installment number field',
  '477': 'Standing order installment transaction requires initialization transaction identifier number',
  '478': 'Standing order installment transaction requires initialization transaction authorization number',
  '479': 'Standing order installment transaction requires initialization transaction date and time fields',
  '480': 'Missing source transaction authorizer field',
  '481': 'Missing units number field when transaction is performed in payment method code different from currency',
  '482': 'In loaded card, regular charge/credit/cancellation/unloading/loading/balance inquiry transaction is allowed',
  '483': 'Transaction with fuel card in fuel terminal requires vehicle number entry',
  '484': 'Entered vehicle number differs from vehicle number burned on magnetic stripe/different bank number from 012/different left digits of branch number from 44',
  '485': 'Vehicle number shorter than 6 digits / differs from vehicle number appearing on channel 2 (position 34 in channel 2) fuel characteristic card of Leumi Card',
  '486': 'There is an obligation to enter meter reading (position 30 in channel 2) fuel characteristic card of Leumi Card',
  '487': 'Only in terminal defined as two-stage fuel can Obligo update be used',
  '489': 'In fuel card, only regular charge transaction is allowed (cancellation transaction forbidden)',
  '490': 'In fuel/fuel club/fuel club cards, transactions can only be performed in fuel terminals',
  '491': 'Transaction including conversion must contain all fields conversion_amount_06, conversion_rate_09, conversion_currency_51',
  '492': 'No conversion on shekel/dollar transactions',
  '493': 'In transaction including benefit, only one of the following fields must be present: discount amount/number of units/% discount',
  '494': 'Different terminal number',
  '495': 'No fallback authorization',
  '496': 'Cannot link credit different from credit credit/payments',
  '497': 'Cannot link to dollar/index in currency different from shekel',
  '498': 'Local Isracard card separator must be in position 18',
  '500': 'Transaction stopped by user',
  '504': 'Mismatch between card data source field and card number field',
  '505': 'Illegal value in transaction type field',
  '506': 'Illegal value in eci field',
  '507': 'Actual transaction amount higher than authorized amount',
  '509': 'Error during writing to transactions file',
  '512': 'Cannot enter authorization received from voice response for this transaction',
  '551': 'Response message does not match request message',
  '552': 'Error in field 55',
  '553': 'Error received from tandem',
  '554': 'Field mcc_18 missing in response message',
  '555': 'Field response_code_25 missing in response message',
  '556': 'Field rrn_37 missing in response message',
  '557': 'Field comp_retailer_num_42 missing in response message',
  '558': 'Field auth_code_43 missing in response message',
  '559': 'Field f39_response_39 missing in response message',
  '560': 'Field authorization_no_38 missing in response message',
  '561': 'Field additional_data_48.solek_auth_no missing/empty in response message',
  '562': 'One of fields conversion_amount_06, conversion_rate_09, conversion_currency_51 missing in response message',
  '563': 'Field value does not match authorization numbers received auth_code_43',
  '564': 'Field additional_amounts54.cashback_amount missing/empty in response message',
  '565': 'Mismatch between field 25 and field 43',
  '566': 'In terminal defined as supporting two-stage fuel, fields 90,119 must be returned',
  '567': 'Fields 25,127 invalid in Obligo update message in terminal defined as two-stage fuel',
  '700': 'Transaction rejected by PinPad device',
  '701': 'PinPad device error',
  '702': 'Invalid com port',
  '703': 'Transaction failed',
  '704': 'Transaction canceled',
  '705': 'Transaction stopped by user',
  '706': 'Wait time too long',
  '707': 'User removed card before transaction completion',
  '708': 'PINPAD_UserRetriesExceeded',
  '709': 'PINPAD_PINPadTimeout',
  '710': 'Communication error with device',
  '711': 'PINPAD_PINPadMessageError',
  '712': 'PINPAD_PINPadNotInitialized',
  '713': 'PINPAD_PINPadCardReadError',
  '714': 'PINPAD_ReaderTimeout',
  '715': 'PINPAD_ReaderCommsError',
  '716': 'PINPAD_ReaderMessageError',
  '717': 'PINPAD_HostMessageError',
  '718': 'PINPAD_HostConfigError',
  '719': 'PINPAD_HostKeyError',
  '720': 'PINPAD_HostConnectError',
  '721': 'PINPAD_HostTransmitError',
  '722': 'PINPAD_HostReceiveError',
  '723': 'PINPAD_HostTimeout',
  '724': 'PINVerificationNotSupportedByCard',
  '725': 'PINVerificationFailed',
  '726': 'Error reading config.xml file',
  '730': 'Device approved transaction contrary to credit decision',
  '731': 'Card number not found. Please enter the credit card number again.',
  '800': 'Transaction canceled.',
  '951': 'PayPal protocol error.',
  '952': 'PayPal payment was not completed. The browser was closed or the communication with the browser was disconnected.',
  '954': 'PayPal payment failed.',
  '997': 'General failure.',
  '998': 'Transactions file failure. Please contact Tranzila support.',
} as const

// Success operation codes
export const SUCCESS_CODES = ['000', '001', '002', '003'] as const

// Function to get error message by code
export const getPaymentErrorMessage = (code: string): string => {
  return PAYMENT_ERROR_CODES[code as keyof typeof PAYMENT_ERROR_CODES] || `Payment error (code: ${code})`
}

export enum PAYMENT_ERROR_CODES_ENUM {
  SUCCESS = '000',
  BLOCKED_CARD = '001',
  STOLEN_CARD = '002',
  CONTACT_CREDIT_COMPANY = '003',
  REFUSAL = '004',
  FORGED_CARD = '005',
  WRONG_CARD_NUMBER = '447',
  WRONG_EXPIRATION_DATE = '416',
  WRONG_CVV = '006',
  EXPIRED_CARD = '415',
}