import { Footer, Header } from '@/src/widgets'
import type { Metadata } from 'next'
import { Arima } from 'next/font/google'
import 'swiper/css'
import 'swiper/css/bundle'
import 'swiper/css/navigation'
import 'swiper/css/pagination'

import './globals.css'

const arima = Arima({
  variable: '--font-arima',
  subsets: ['latin'],
  weight: ['100', '200', '300', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${arima.className} antialiased`}>
        <main className='flex min-h-screen flex-col justify-between'>
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  )
}
